apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBl+HiVvLXGG9Y4tYUQ5I7ruIk5ICfrOaRGjRRpU72hZSpf7DfuiXZKZeA3ZlVpL92rDCOpCydKl/j8yvEaOcIxLyqaTThQ7MSE9ZUReoBDAhvBvt4ObJshTEKmS0vR5sF/5tEtoVy1vT6CVnfstSWHp6/3whegWHqeZTbOEDFeCPZOsC3D8Jx0qtv/1XmQf3nmB6BRwvDStJ9ZWIDszuDUdNV0ZA2cZsZdW4depuMcdOkLThx/FSFyRinPbKthJWFUlIyuMLBHphFZEWDNkXqA0B+T5CVqEBy3Xh0hfe4b3Q3ssxncpnAjzm4gMcCeSS5MPOhb+ulwZHP2zvI2221LPKbtWUk+BLMcxPME+I2f751RmDfZfB+8TdtvSlsXx3jUXFjcqKrwhd9eBxlZBy1QFQ6HLVZokkIxRJVTNH8LXyzgtWDyGk/FZTa+hU70iGmVV+zrBfy94m0B2bvh0yaL5NDNGSb0xQlXkQSx5MhYIWl7wlDXK+M+plUwDOUYwx12/6YQ0ISH0U4y46QcWc55/y9qHRC1QMLSe5TenaadQ+/KXiLuzt8TFb4IO9MKdNeFQDNWirLjW0/mlwNBCGIuciRCH3F5qbQW0IyFk3TCCciKGhAPe6IqOLc829IRA4xqph88UVeSlsGij/D4eAlK1338y94SWqzpgd6kzucjPvh13jxWh1IEZmfZ67M5SwyGUirvfV6+xQ==
    DB_USER: AgBUBf17i5UMcdhADNnYSu8uHCyDt57jM5YtqnXXl2T8aQaE9f5tB9JG1I89KaJd54U0a6HOHAxY0VnvgSlEzGKAyOdEo7rEaxH9iZFWgFDGwfV46PY9D8+kFh/JB22Mu6PaVLanikE009HkICP+FNayI2huVfPFwz1YappQMn69/4UWE76X8+RqpFiYxwR99f3d4ZiNurltjsXmviTKprUpT/aP9nVVVH8owcc07K+MRN7bcldDy1CUUHJBSPHAhBcxog/KQfta7ECYhghT7UDv1RY5EDjlXoc3qJaYrA7Coed8FJUrZCXfnV2GmVb62Y3+o89s9k4aF5RPknSywoVHPuq9rb4E4SbycQGBtkuANETidWSWAFbgQlLBJDuDNH1+u+1KFLHDMNkSLQgs+l8LAkaGyxBbFAFnGd8r6GxcxvtUT9wUyvBZDyztLTty4q2GZ5TqAR8fDmgsajx/bLXc6pQ+vP9NvRfWk06UyQVzxWayrkH+pG3oIS7/w6iZACgbfeNW6sjf1gET0O+IkABsD0P0DL8VKb1fhhK+SCAPhz2eCU69OslfO9U/rmu2l7ViDGSPkVmSJkb90zyKAi8FTJOl2ejnBj9Jhb6ciyPxt86SWmNdrQL+9Ciur3p258eCo2/V7c8ZUNzXrgUBIKq1lBX9kndxN120QPkV2T26iyitCAxby11/CzQg5YCefuxxtFhuOY8xoQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

