apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgCfYnIX/zzKHIlzLfMcbsWkBJ2n0FQjKBjEDVj7V+5gZjPNLWt53sCOfrQkSTS3coHyhB6oRTQ2twhHnUJAOCUqJ2f0utrj/5xhZlDoqNqgxLk9zRUKph8txAessMY/Uq7X9q/ri4oK/l4hra8dE6isiGbkQDrUo/g0GtAX/a5xHIYbhkvBELRigC78SczczocH8Q4CDNEjJofYKc5vtN6JP8s0tniyY0HNWQ4p6Vqy5X/U5z2j4hZ0pWTqPzhZrRx9LWCqJr6VJI7PeSsicyutxlt7TmNnV2rLPoeKCz/OYjpTOPhl5ID/yqq3rJRwcmnqL3MllGylJFEEW3QPG2NUFDPAvuP0M/5Vclw/z9bmQbFfNIgB+iesvLbm24P0Y9yz4tmHhkdeyS4xmiQlczcptlqTRPg7jDv2e7RClLbbbFNNb1wqvSkaiyzWLQyXK7dqFRlDrY2GOpJ91AnaJofs0F+uPWfiEpWRgnMAB56+jdiwZJvFHIN1+/Rb2AjyolH9hWK6ZDlp4otaHWoiEdzdKqd/3YPD4NaSHEb5dc8oRqySDSO+FFwxigGoGz6cDPnGg8VFcO3xjleuL4gPV1QTs/cgcybs/z5F7MwKj/2m/hsd6SIz9BnjM45mv2+mUO4Rfe7aXb6CpUWrBv/5vnWaXmdkzlQYOfPT0Ze0njU0r+lvg/MUu1Lwfni8nUCR/Spi/85eq78pVQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

