apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAfRISMrOQDGEyu7CBhdTjWsg7IYI+sOpjpwvnyOAIO7KwfMP38itzWj05I2IS9O4mYKTKi0XIBOB0radK0jrhCFXNrs9ztzdSSl0Yx9R4b/aQjk8WbDpIm8Y9X9T1VuJR5owFyCppvJEAaeUzgZupi8CXymsrPxse558GPYLmRxw6cjZnG/dyO3ZoRKKe9G67cAiL3PKqGc/8iLcc1Txj7i7zrO2/qhrXDxZDOECDK+MmzIK5XF81ktghgZT7BuQW7pMSUedgbECLGH2ODAibRYhLfwt9alkRsWdeUYZs0ZrEqaG9jwuVxzyp6UAC5P7dnGItsGhST4ZQ25gst2MNZgboSQ03nCdMCAJ6cuzlpoRE4uX3Rd+5ACQV369knly2YzLnmzMQm/Xif4EibSS13nwEUzdKvUQ2ip0OlPgJjHi6OQyficucacNIm1x/Vdpza0ZCvJ9w3YR6l0kwepGkDfK4N7E34OIWG0xpyxhZ4DiYJ9I92BQ5HUZuXTGwe1bb+mx8fPJZ5q0HNdVxRvABu8a1EZbZMHfVGO+TqEtJLdeAZID7NLYtnpi2XI7bpV+UCTjJZu6M2Bt/Uu4uostn7h45g1U/sopn2n+8XUcYF16sV1l+cVXBnDmPX4Q/mC08sPn84bpeVVOlwK4Dj55/Sdyk2b5EIt+lnNYyRPhO4mgzPFQsIyJUzv8ve56hU+CatbcuIPzSspw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

